services:
  - type: web
    name: do-an-tot-nghiep
    env: python
    region: oregon
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server.app:app
    envVars:
      - key: ORS_API_KEY
        sync: false
